version: 1

env:
  - "CGO_ENABLED=0"

flags:
  - "-tags=netgo"
  - "-trimpath"

builds:
  - id: gb
    binary: gb
    main: .
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s"
      - "-w"
      - "-X main.Version={{ .Env.VERSION }}"
      - "-X main.BuildTime={{ .Env.BUILD_TIME }}"
      - "-X main.Commit={{ .Env.COMMIT }}"
