# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  default:
    desc: "Build for current platform"
    sources:
      - "{{.ROOT_DIR}}/**/*.go"
      - "{{.ROOT_DIR}}/go.mod"
      - "{{.ROOT_DIR}}/go.sum"
    generates:
      - "{{.ROOT_DIR}}/bin/{{.BINARY_NAME}}{{exeExt}}"
    cmds:
      - mkdir -p {{.ROOT_DIR}}/bin
      - cd {{.ROOT_DIR}} && go build {{.LDFLAGS}} -o bin/{{.BINARY_NAME}}{{exeExt}} .

  all:
    desc: "Build for all platforms"
    deps:
      - linux
      - darwin

  linux:
    desc: "Build for Linux (amd64, arm64)"
    sources:
      - "{{.ROOT_DIR}}/**/*.go"
      - "{{.ROOT_DIR}}/go.mod"
      - "{{.ROOT_DIR}}/go.sum"
    generates:
      - "{{.ROOT_DIR}}/bin/{{.BINARY_NAME}}-linux-amd64"
      - "{{.ROOT_DIR}}/bin/{{.BINARY_NAME}}-linux-arm64"
    cmds:
      - mkdir -p {{.ROOT_DIR}}/bin
      - cd {{.ROOT_DIR}} && GOOS=linux GOARCH=amd64 go build {{.LDFLAGS}} -o bin/{{.BINARY_NAME}}-linux-amd64 .
      - cd {{.ROOT_DIR}} && GOOS=linux GOARCH=arm64 go build {{.LDFLAGS}} -o bin/{{.BINARY_NAME}}-linux-arm64 .

  darwin:
    desc: "Build for macOS (amd64, arm64)"
    sources:
      - "{{.ROOT_DIR}}/**/*.go"
      - "{{.ROOT_DIR}}/go.mod"
      - "{{.ROOT_DIR}}/go.sum"
    generates:
      - "{{.ROOT_DIR}}/bin/{{.BINARY_NAME}}-darwin-amd64"
      - "{{.ROOT_DIR}}/bin/{{.BINARY_NAME}}-darwin-arm64"
    cmds:
      - mkdir -p {{.ROOT_DIR}}/bin
      - cd {{.ROOT_DIR}} && GOOS=darwin GOARCH=amd64 go build {{.LDFLAGS}} -o bin/{{.BINARY_NAME}}-darwin-amd64 .
      - cd {{.ROOT_DIR}} && GOOS=darwin GOARCH=arm64 go build {{.LDFLAGS}} -o bin/{{.BINARY_NAME}}-darwin-arm64 .

  clean:
    desc: "Remove build artifacts"
    cmds:
      - find {{.ROOT_DIR}}/bin/ -mindepth 1 -not -name ".gitkeep" -delete

  watch:
    desc: "Watch for changes and rebuild"
    watch: true
    sources:
      - "{{.ROOT_DIR}}/**/*.go"
    cmds:
      - task: default
